config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#new'
  resource :session, only: [:create]
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    get '/home', to: 'users/static_pages#home'
    get '/timeline', to: 'users/static_pages#timeline', as: '/timeline'
    get '/friends', to: 'users/static_pages#friends', as: '/friends'
    get '/photos', to: 'users/static_pages#photos', as: '/photos'
    resource :profile, only: [:show, :edit, :update, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user, inverse_of: :profile

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_one :profile, inverse_of: :user

  accepts_nested_attributes_for :profile, reject_if: :all_blank

  validates :password, length: {in: 3..20}, allow_nil: true
  validates :email, presence: true, uniqueness: true

  before_create :generate_token

  # generate token for persisted login
  def generate_token
    begin
      self[:auth_token] = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: self[:auth_token])
  end

  # regenerate tokens whenever needed
  def regenerate_auth_token
    self.auth_token = nil
    generate_token
    save!
  end


private



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  # before_action :require_login, except: [:new, :create]

private

  def set_user
    @current_user = User.find_by_auth_token(cookies[:auth_token])
  end


  def sign_in(user)
    user.regenerate_auth_token
    cookies[:auth_token] = user.auth_token
    @current_user = user
  end


  def permanent_sign_in(user)
    user.regenerate_auth_token
    cookies.permanent[:auth_token] = user.auth_token
    @current_user = user
  end


  def sign_out
    @current_user = nil
    cookies.delete(:auth_token)
  end


  def signed_in_user?
    !!@current_user
  end
  helper_method :signed_in_user?

  def current_user
    @current_user ||=
    User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user


  def require_login
    unless signed_in_user?
      flash[:danger] = "Not Authorized, please sign in!"
      redirect_to root_path
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def my_feed
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_user


  def create
  end


  def show
  end


  def edit
    @profile = @current_user.profile
  end


  def update
    @profile = @current_user.profile
    if @profile.update!(profile_params)
      flash[:success] = "'About Me' successfully updated!"
      redirect_to user_profile_path
    else
      flash[:danger] = "Unable to update 'About Me'"
      render :edit
    end
  end


  def destroy
  end

private

    def profile_params
      params.require(:profile).permit( :college,
                                       :hometown,
                                       :current_town,
                                       :telephone,
                                       :words_to_live_by,
                                       :about_me )
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
    @user = User.find_by_email(params[:email])
  end


  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      if params[:remember_me]
        permanent_sign_in(@user)
        flash[:success] = "User Signed in Successfully!"
        redirect_to user_timeline_path(@user)
      else
        sign_in(@user)
        flash[:success] = "User Signed in Successfully!"
        redirect_to user_timeline_path(@user)
      end
    else
      flash[:danger] = "Unable to sign in - Please check your email and password."
      redirect_to root_path
    end
  end

  def destroy
    sign_out
    flash[:success] = "Logged Out Successfully!"
    redirect_to root_path
  end



end

app/controllers/static_pages1_controller.rb
class StaticPages1Controller < ApplicationController
  def timeline
  end
  def photos
  end
  def about
  end
  def about_edit
  end
  def friends
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def timeline
    
  end

  def friends

  end

  def about

  end

  def photos

  end

  def about_edit

  end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def timeline
  end

  def about
  end

  def friends
  end

  def photos
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, except: [:new, :create]
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
    @profile = @user.build_profile
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = "Created New User Successfully!"
      redirect_to user_timeline_path(@user)
    else
      flash[:error] = "Unable to Create New User"
      render :new
    end
  end


  def edit
  end


  def update
    if @current_user.update(user_params)
      flash[:success] = "'About Me' successfully updated!"
      redirect_to user_profile_path(@current_user)
    else
      flash[:danger] = "Unable to update 'About Me'"
      render :edit
    end
  end


  def show
  end


  def destroy
  end

private


  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, { profile_attributes: [ :id, :last_name, :first_name, :birthday, :gender, :college, :hometown, :current_town, :telephone, :about_me, :words_to_live_by, :_destroy] })
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def display_form_errors(resource, field)
    unless resource.errors[field].empty?
      content_tag(:span, class: "error-msg") do
        "#{field.to_s.titleize} #{resource.errors[field].first}"
      end
    end
  end

  

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages1_helper.rb
module StaticPages1Helper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/about/edit/_basic_info.html.erb
<h1 class="heading">Basic Information</h1>
<div id="basic-info-table">
  <div class="form-group">
    <%= profile_fields.label :birthday %>
    <%= profile_fields.date_field :birthday %>
  </div>
  <div class="form-group">
    <%= profile_fields.label :college %>
    <%= profile_fields.text_field :college %>
  </div>
  <div class="form-group">
    <%= profile_fields.label :hometown %>
    <%= profile_fields.text_field :hometown %>
  </div>
  <div class="form-group">
    <%= profile_fields.label :current_town %>
    <%= profile_fields.text_field :current_town %>
  </div>
</div>

app/views/profiles/about/edit/_contact_info.html.erb
<h1 class="heading">Contact Information</h1>
<div id="contact-info-table">
  <div class="form-group">
    <%= user_fields.label :email %>
    <%= user_fields.text_field :email %>
  </div>
  <div class="form-group">
    <%= profile_fields.label :telephone %>
    <%= profile_fields.text_field :telephone %>
  </div>
</div>

app/views/profiles/about/edit/_leftside.html.erb
<div class="left-side">

  <%= render partial: 'profiles/about/edit/basic_info',
              locals: { profile_fields: profile_fields } %>

  <%= render partial: 'profiles/about/edit/contact_info',
              locals: { profile_fields: profile_fields, user_fields: user_fields } %>

</div>

app/views/profiles/about/edit/_rightside.html.erb
<div class="about-me-blurbs right-side">
  <h1 class="heading">Words to Live by</h1>
    <%= profile_fields.text_field :words_to_live_by, size: 30 %>
  <h1 class="heading about-me">About Me</h1>
    <%= profile_fields.text_field :about_me, size: 30 %>
</div>

app/views/shared/_about_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">
    About
  </div>
  <div class="panel-body">
    <p><strong>Born on</strong>: July 31st, 1990</p>
    <p><strong>Went to School on</strong>: Hogwarts</p>
    <p><strong>Hometown</strong>: Godrick's Hollow, England</p>
    <p><strong>Currently lives</strong>: Godrick's Hollow</p>
  </div>
</div>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="dp">
      <%= link_to about_path, class: "dp-profile-name" do %>
        <img class="dp-img" src="https://s3.amazonaws.com/viking_education/web_development/web_app_eng/harry_potter_small.jpg" alt="user image">
        Henry Potter
        <i class="glyphicon glyphicon-ok"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_logged_in_navbar.html.erb
<div class="loggedin-nav">
  <div class="far-left">
    <h1 class="loggedin-brand white-text">Danebook</h1>
  </div>
  <input class="search-bar" type="text" placeholder="Search for Users">
  <div>
    <%= link_to current_user.email, user_timeline_path(current_user), class: "far-right white-text"%>
    <%= link_to "Logout", logout_path, method: "DELETE", class: "far-right white-text" %>
  </div>
</div>

app/views/shared/_logged_navbar.html.erb
<!--NAVIGATION-->
<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#login-navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo-container" href="home.html">
                <img src="assets/danish_flag.gif" alt="Brand">
                <h3>Danebook</h3>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="login-navbar-collapse">
            <form class="navbar-form navbar-left search-form">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search for User">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">Harry</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>

app/views/shared/_login_form.html.erb
<!-- Login Form -->
<div id="navbar-collapse" class="collapse navbar-collapse">

	<form id="navbar-signin" class="navbar-form form-inline navbar-right">
		<div class="form-group">
			<input type="email" name="email" class="form-control" placeholder="Email"/>
		</div>
		<div class="form-group">
			<input type="password" name="password" class="form-control" placeholder="Password">
		</div>
		<button type="submit" class="btn btn-default">Sign In</button>
	</form>

</div>

app/views/shared/_make_a_post.html.erb
<article class="post-copied">
  <h3 class="grey-back-ground">Post</h3>
    <div class="outer-post-area">
      <textarea class="make-new-post" placeholder="Tell us what's on your mind..."></textarea>
    </div>
    <div class="submit-post-button-area grey-back-ground" align="right">
      <input type="submit" value="Post" method="post" action="#" class="submit-post-button">
    </div>
</article>

app/views/shared/_navbar.html.erb
<% if signed_in_user? %>
  <nav>
    <%= render partial: 'shared/logged_in_navbar', locals: { current_user: @current_user } %>
  </nav>
<% else %>
  <nav>
    <%= render 'shared/not_logged_in_navbar' %>
  </nav>
<% end %>

app/views/shared/_navbar_home.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Danebook</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="email" id="userEmail" class="form-control" placeholder="E-mail">
        </div>
        <div class="form-group">
          <input type="password" id="userPassword" class="form-control" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-success">Log In</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_navbar_homepage.html.erb
<% if current_page?(static_pages_path) %>
  <% on_homepage = true %>
<% else %>
  <% on_homepage = false %>
<% end %>

<% if on_homepage %>
  <div class="homepage">
    <div class="navbar">
      <%= link_to static_pages_path do %>
        Danebook
      <% end %>
      <div class="login-container navbar-form navbar-right">
        <input type="text" class="form-control" id="emailInput1" placeholder="Email">
        <input type="text" class="form-control" id="emailInput2" placeholder="Password">
        <button type="button" class="btn btn-info">Sign in</button>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<section class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="cover-top">
      <div class="row" id="banner-row">
        <div class="col-md-12">
          <div class="bg-container"></div>
          <!-- <img class="img-rounded img-responsive" id="hogwarts" src="img/hogwarts_small.jpg" alt="hogwarts" /> -->
        </div>
        <div id="avatar">
          <!-- <img class="img-responsive" src="img/harry_potter_small.jpg" alt="" /> -->
          <%= image_tag('harry_potter_small', class: "img-responsive") %>
        </div>
      </div>
      <!-- banner part finish -->
      <!-- nav part begin -->
      <div class="row" id="add-margin-top">
        <div id="edit-profile" class="col-sm-2 col-md-push-10">
          <%= link_to 'Edit Profile', about_edit_path %>
        </div>
        <div class="col-sm-8 col-sm-offset-2 col-md-pull-2 center-child-block">
          <ul class="nav nav-pills" id="main-navigation">
              <li role="navigation" class="<%= active_class(timeline_path) %>"><%= link_to 'Timeline', timeline_path %></li>
              <li role="navigation" class="<%= active_class(about_path) %>"><%= link_to 'About', about_path %></li>
              <li role="navigation" class="<%= active_class(photos_path) %>">
                <%= link_to photos_path do %>
                  Photos<span class="badge">144</span>
                <% end %>
              </li>
              <li role="navigation" class="<%= active_class(friends_path) %>">
                <%= link_to friends_path do %>
                  Friends<span class="badge">251</span>
                <% end %>
              </li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/shared/_not_logged_in_navbar.html.erb
<div class="not-loggedin-nav">
  <h1 class="not-loggedin-brand white-text">Danebook</h1>
  <%= render 'sessions/login_form' %>
</div>

app/views/shared/_post.html.erb
<div class="panel">
  <div class="panel-heading">
    <div class="media">
      <div class="pull-left">
        <%= link_to "#" do %>
          <img class="user-thumbnail" src="https://s3.amazonaws.com/viking_education/web_development/web_app_eng/user_silhouette_generic.gif" alt="...">
        <% end %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to "Hermione Granger", "#" %></h4>
        <span class="text-info">Posted on Thursday 6/1/2014</span>
      </div>
    </div>

  </div>
  <div class="panel-body">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
  <div class="panel-footer">
    <p>
      <%= link_to "Like", "#" %> |
      <%= link_to "Comment", "#" %> |
      <%= link_to "Delete", "#" %>
    </p>
  </div>
</div>

app/views/shared/_signed_out_navbar.html.erb
<nav class = "navbar navbar-default">
  <div class = "container">
    <div class = "navbar-header">

      <button type="button" class="btn btn-navbar navbar-toggle collapsed" id = "toggle-colors" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class = "navbar-brand" id = "brand-color" href="#">
        Danebook
      </a>
    </div>

    <div id = "navbar" class = "navbar-collapse collapse">

      <form class="navbar-form navbar-right">
          <div class="form-group">
            <h6>Email</h6>
            <input type="text" placeholder="example@email.com" class="form-control">
          </div>

          <div class="form-group">
            <h6>Password</h6>
            <input type="password" placeholder="Password" class="form-control">
          </div>

          <button type="submit" class="btn btn-primary">Sign in</button>
        </form>

    </div>
  </div>

</nav>

app/views/shared/_sub_navbar.html.erb
<nav class="sub-navigation" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sub-nav-collapse" aria-expanded="false"><span class="caret"></span>Menu
        </button>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="sub-nav-collapse">
            <ul class="nav nav-pills">
                <li role="presentation" class="<%= current_page?(action: 'timeline') ? 'active' : ' ' %>">
                    <%= link_to "Timeline", timeline_path %>
                </li>
                <li role="presentation" class="<%= current_page?(action: 'about') ? 'active' : ' ' %>">
                    <%= link_to "About", about_path %>
                </li>
                <li role="presentation" class="<%= current_page?(action: 'photos') ? 'active' : ' ' %>">
                    <%= link_to "Photos<span class='badge'>(123)</span>".html_safe, photos_path %>
                </li>
                <li role="presentation" class="<%= current_page?(action: 'friends') ? 'active' : ' ' %>">
                    <%= link_to "Friends<span class='badge'>(542)</span>".html_safe, friends_path %>
                </li>
                <li class="edit-profile pull-right">
                    <%= link_to "Edit Profile", about_edit_path %>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>